---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaoskube
  namespace: <YOUR-NAMESPACE-HERE>
  labels:
    app: chaoskube
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: chaoskube
  template:
    metadata:
      labels:
        app: chaoskube
    spec:
      serviceAccountName: chaoskube
      containers:
      - name: chaoskube
        image: quay.io/linki/chaoskube:v0.9.0
        args:
        # kill a pod every 1 minute
        - --interval=1m # Change the interval here
        # only target pods having label as django environment
        - --labels=app=django
        # only consider pods with this annotation
        #- --annotations=chaos.alpha.kubernetes.io/enabled=true
        # exclude all pods in the kube-system namespace
        - --namespaces=<YOUR-NAMESPACE-HERE>
        # don't kill anything on weekends
        - --excluded-weekdays=Sat,Sun
        # don't kill anything during the night or at lunchtime
        #- --excluded-times-of-day=22:00-08:00,11:00-13:00
        # don't kill anything as a joke or on christmas eve
        #- --excluded-days-of-year=Apr1,Dec24
        # let's make sure we all agree on what the above times mean
        #- --timezone=UTC
        # terminate pods for real: this disables dry-run mode which is on by default
        - --no-dry-run

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaoskube
  namespace: <YOUR-NAMESPACE-HERE>
  labels:
    app: chaoskube

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaoskube
  namespace: <YOUR-NAMESPACE-HERE>
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaoskube-<YOUR-NAMESPACE-HERE>
  namespace: <YOUR-NAMESPACE-HERE>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chaoskube
subjects:
- kind: ServiceAccount
  name: chaoskube
  namespace: <YOUR-NAMESPACE-HERE>
